### ISSUE TITLE
Older DStability stix files cannot be read

### ISSUE THREAD

**Issue by breinbaas** [Deltares/GEOLib#125]
Reading older stix files will generate 'ValueError("Can't listdir a file")'

Short solution is to manually open the file in DStability and save it again but this would be tedious if you have a lot of old files (which people probably have). 

`D:\Documents\Development\Python\ontgrondingskuilen\.env\Lib\site-packages\shapely\set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
Traceback (most recent call last):
  
  File "D:\Documents\Development\Github\GEOLib\geolib\models\dstability\dstability_parserprovider.py", line 93, in parse
    ds = super().parse(path)
         ^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Development\Github\GEOLib\geolib\models\dstability\dstability_parserprovider.py", line 37, in parse
    ds[field] = self.__parse_folder(element_type, filepath / "")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Development\Github\GEOLib\geolib\models\dstability\dstability_parserprovider.py", line 53, in __parse_folder
    files = list(folder.iterdir())
                 ^^^^^^^^^^^^^^^^
  File "D:\Documents\Development\Python\ontgrondingskuilen\.env\Lib\site-packages\zipp\__init__.py", line 347, in iterdir        
    raise ValueError("Can't listdir a file")
ValueError: Can't listdir a file`

**Comment by breinbaas** [comment]
This probably has to do with the stages / scenarios difference

**Comment by carloslubbers** [comment]
@breinbaas As part of the 2023.01 release, there is a "D-GEO Suite Stability Migration Console.exe" included as well, you can call this one to automatically convert files before opening them in your own scripts or GEOLib. Could you try to use this and see if it works to get your files to work again?

**Comment by breinbaas** [comment]
That works, I created a small [script](https://gist.github.com/breinbaas/96799a68206161d8e2aff22a5917fc80) for it so others can use it as well. Thx @carloslubbers
